services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  DirectMailTeam\DirectMail\:
    resource: '../Classes/*'
    
  DirectMailTeam\DirectMail\Command\InvokeMailerEngineCommand:
    tags:
      - name: 'console.command'
        command: 'directmail:invokemailerengine'
        description: 'Invoke Mailer Engine of EXT:directmail'
  DirectMailTeam\DirectMail\Command\DirectmailCommand:
    tags:
      - name: 'console.command'
        command: 'directmail:mailingqueue'
        description: 'This command invokes dmailer in order to process queued messages.'
  DirectMailTeam\DirectMail\Command\AnalyzeBounceMailCommand:
    tags:
      - name: 'console.command'
        command: 'directmail:analyzebouncemail'
        description: 'This command will get bounce mail from the configured mailbox.'